require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'config/initializers/rswag-api.rb'
    - 'config/initializers/rswag-ui.rb'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'bin/bundle'

Metrics/AbcSize:
  Exclude:
    - 'bin/bundle'
    - 'app/controllers/api/v1/authentication_controller.rb'

Metrics/MethodLength:
  Max: 11
  Exclude:
    - 'bin/bundle'
    - 'app/controllers/api/v1/authentication_controller.rb'

Layout/EndOfLine:
  Enabled: False

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Exclude:
    

Lint/DuplicateBranch:
  Exclude:
    - 'app/controllers/api/v1/authentication_controller.rb'

Metrics/ClassLength:
  Exclude:
    

Metrics/ParameterLists:
  Max: 18

Rails/HasAndBelongsToMany:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/HashSyntax:
  Exclude:
    - 'spec/requests/api/v1/authentication_spec.rb'
    - 'app/controllers/api/v1/authentication_controller.rb'

Style/Semicolon:
  Exclude:
    

Naming/AccessorMethodName:
  Exclude:
    

Naming/MethodParameterName:
  Exclude:
    

Naming/MethodName:
  Exclude:
    

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/initializers/version.rb'

Rails/FilePath:
  EnforcedStyle: arguments

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_invitation_token

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/VariableName:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:

RSpec/AnyInstance:
  Exclude:
    
RSpec/ScatteredSetup:
  Exclude:
  - 'spec/requests/api/v1/authentication_spec.rb'