default: &default
  adapter: postgresql
  encoding: unicode
  username: api
  password: api
  # url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>
  database: api_rails_development


test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>
  database: api_rails_test

# production:
  <<: *default
  database: marketplace_production
  username: marketplace
  password: <%= ENV["MARKETPLACE_DATABASE_PASSWORD"] %>
