default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  # url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>
  database: api_rails_development


test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>
  database: api_rails_test

production:
  <<: *default
  database: api_marketplace_production
  url: <%= ENV['PROD_DATABASE_URL'] %>
